vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
